# Generated by Django 5.0.1 on 2024-03-05 17:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_user_phone_user_phone_number_alter_user_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminuser',
            options={'verbose_name': 'Admin_User'},
        ),
        migrations.CreateModel(
            name='CheckingAccount',
            fields=[
                ('account_number', models.DecimalField(decimal_places=0, max_digits=20, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(10000000000000000000)])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_number', models.DecimalField(decimal_places=0, max_digits=20, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1000000000000000)])),
                ('balance', models.FloatField()),
                ('expiration_date', models.DateField()),
                ('cvv_code', models.IntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(999)])),
                ('checking_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.checkingaccount')),
            ],
        ),
    ]
