# Generated by Django 4.2.11 on 2024-03-11 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_user_phone_user_phone_number_alter_user_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminuser',
            options={'verbose_name': 'Admin_User'},
        ),
        migrations.CreateModel(
            name='CheckingAccount',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('account_number', models.CharField(max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('card_number', models.CharField(max_length=16)),
                ('expiration_date', models.DateField()),
                ('cvv_code', models.CharField(max_length=3)),
                ('checking_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.checkingaccount')),
            ],
        ),
    ]
