# Generated by Django 4.2.11 on 2024-03-06 05:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_adminuser_options_checkingaccount_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.DecimalField(decimal_places=0, max_digits=16, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1000000000000000)]),
        ),
    ]
