# Generated by Django 4.2.11 on 2024-03-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_card_id_alter_checkingaccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='checkingaccount',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
