# Generated by Django 4.2.11 on 2024-03-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_card_id_alter_checkingaccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='checkingaccount',
            name='account_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
