# Generated by Django 4.2.11 on 2024-04-24 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_user_favorite_users"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("money_amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "receiver_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receiver_account",
                        to="app.checkingaccount",
                    ),
                ),
                (
                    "sender_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sender_account",
                        to="app.checkingaccount",
                    ),
                ),
            ],
        ),
    ]
