# Generated by Django 4.2.11 on 2024-04-29 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_alter_transaction_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=63, null=True),
        ),
        migrations.CreateModel(
            name="IssuedToken",
            fields=[
                ("jti", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("revoked", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="refresh_tokens", to="app.user"
                    ),
                ),
            ],
        ),
    ]
