# Generated by Django 4.2.13 on 2024-05-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_alter_user_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="is_viewed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transaction",
            name="postcard",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
