image: docker/compose:alpine-1.29.2

stages:
  - build
  - lint
  - test
  - deploy

before_script:
  - apk add make
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - cp $DOT_ENV $(pwd)/.env

build:
  stage: build
  script:
    - make build push
  tags:
    - job:build
  only:
    - master
    - /^hw[0-9]+/
  environment:
    name: prod

lint:
  stage: lint
  script: make pull lint
  tags:
    - job:lint
  only:
    - master
    - /^hw[0-9]+/
  environment:
    name: prod

test:
  stage: test
  script: make pull test
  tags:
    - job:test
  only:
    - master
    - /^hw[0-9]+/
  environment:
    name: prod

deploy:
  stage: deploy
  script:
    - make pull down migrate collectstatic up
  tags:
    - job:deploy
  only:
    - master
    - /^hw[0-9]+/
  environment:
    name: prod
  when: manual