services:
  db:
    image: postgres:14.2-alpine
    container_name: db
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    container_name: app
    build: .
    command: python src/manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

  bot:
    build: .
    container_name: bot
    command: python src/manage.py start_bot
    env_file:
      - .env
    depends_on:
      - db

volumes:
  pgdata:
